# Generated by Django 3.0.5 on 2020-04-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management_app', '0002_auto_20200418_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='discount',
        ),
        migrations.AddField(
            model_name='deal',
            name='discount_persentage',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
            preserve_default=False,
        ),
    ]
