# Generated by Django 3.0.5 on 2020-04-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credittransaction',
            name='credit_before',
        ),
    ]
