# Generated by Django 3.0.5 on 2020-04-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_role_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='name',
        ),
    ]
