# Generated by Django 3.0.5 on 2020-04-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_auto_20200416_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='credit',
        ),
    ]
